### ISSUE TITLE
Homebridge 시작 시 ApiException

### ISSUE THREAD

**Issue by sw2719** [kyle-seongwoo-jun/homebridge-navien-smart#14]
안녕하세요, 플러그인을 써볼려고 설치했는데 아래 첨부한 로그의 오류가 나옵니다.
Proxyman으로 확인해봤는데 API 주소가 `https://nskr.naviensmartcontrol.com/api/v2.0`으로 바뀌었네요. 확인 부탁드립니다.

```
[10/10/2024, 9:48:15 PM] [NavienSmart] ApiException: code: undefined, message: undefined
```

**Environment:**

* **Plugin Version**: v1.5.0
* **Homebridge Version**: v1.8.4
* **Node.js Version**: v20.18.0
* **NPM Version**: 10.8.2
* **Operating System**: Docker (ubuntu)

**Comment by kyle-seongwoo-jun** [comment]
최근 전기장판을 사용하지 않다보니 문제가 있는지 몰랐네요! 확인해보겠습니다

**Comment by kyle-seongwoo-jun** [comment]
@sw2719 수정한 [1.6.0](https://www.npmjs.com/package/homebridge-navien-smart/v/1.6.0) 버전을 릴리즈했는데 혹시 사용해보시고 문제 있으시면 말씀해주세요!
